application: gaehellowzj01
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /(.*)
  script: main.app

admin-console:
 pages:
- name: Appstats UI
  url: /stats

builtins:
- appstats: on